resolver: lts-10.10
packages:
  - "."
  - ../common

allow-different-user: true
extra-deps:
  - miso-0.21.2.0
  # Pin Aeson to the version the frontend uses.
  - aeson-1.1.2.0
  # Settle on a more recent version of Servant with the frontend.
  # NOTE: We are using <0.13 because later versions bumped the Aeson dependency.
  - servant-0.12.1
  - servant-server-0.12
  - cabal-doctest-1.0.6
  - phoityne-vscode-0.0.22.0
  - github: tneisinger/haskell-tictactoe
    commit: 98305a1c97c5e5bf62f9ae027a0c6fbdfc44de32
